# Site settings
title: Νεοελληνικά ρήματα
description: A reference of modern Greek verbs with active, passive, and middle voices
baseurl: "/greek"
url: "https://audetto.github.io"

# Markdown & plugins
markdown: kramdown
kramdown:
  input: GFM
